# .github/workflows/manual-patch-run.yml
name: Run Patch Job Manually

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Укажи ветку вида patch/**'
        required: true

jobs:
  validate-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка имени ветки
        run: |
          echo "Ветка: ${{ github.event.inputs.branch }}"
          if [[ "${{ github.event.inputs.branch }}" != patch/* ]]; then
            echo "❌ Ветка должна начинаться с 'patch/'"
            exit 1
          fi
          echo "✅ Ветка прошла проверку"

      - name: Checkout указанной ветки
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Выполнить кастомную задачу
        run: |
          echo "Выполняем job для ветки ${{ github.event.inputs.branch }}"
