name: Manual Patch Job

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Укажи имя ветки (только patch/**)'
        required: true

jobs:
  validate-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка ветки
        run: |
          echo "🔎 Ветка для запуска: ${{ github.event.inputs.branch }}"
          if [[ "${{ github.event.inputs.branch }}" != patch/* ]]; then
            echo "❌ Ошибка: ветка должна начинаться с 'patch/'"
            exit 1
          fi
          echo "✅ Ветка прошла проверку"

      - name: Checkout указанной ветки
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Выполнение кастомного действия
        run: |
          echo "🚀 Запуск задачи на ветке ${{ github.event.inputs.branch }}"
          # Вставь свою кастомную логику сюда
